packages:
  - "packages/*"
  - "tests/*"
  # apps and packages directories have been removed

catalog:
  # TypeScript and build tools
  typescript: ^5.8.2
  tsup: ^8.4.0
  "@types/node": ^20.11.24
  
  # Testing
  vitest: ^3.1.1
  "@vitest/coverage-v8": ^3.1.1
  "@vitest/ui": ^3.1.1
  
  # Runtime dependencies
  axios: ^1.6.7
  zod: ^3.22.4
  
  # Tooling
  prettier: ^3.5.3
  turbo: ^2.5.0
  
  # Changeset for versioning
  "@changesets/cli": ^2.29.2
  "@changesets/changelog-github": ^0.5.1
